### ISSUE TITLE
Error when testing deployR: can not open connection

### ISSUE THREAD

**Issue by ouzor** [warmdev/deployr-docker#3]
I installed the deployR docker on my OSX, and everything went well, even the deployR diagnostics showed that everything was fine. 

But when I tried to run the Test Analytics part here: http://deployr.revolutionanalytics.com/documents/getting-started/data-scientist/#test I got an error (can not open connection) when trying to run the ccFraudScore.R file in the test phase.

I suspected that this might be a port issue, and indeed using this command to run docker with all the necessary ports open fixed the problem:

```
docker run -d -p 7400-7406:7400-7406 deployr
```

Did you try running the Test Analytics? If not, please try, and if you encounter the same error, please consider this fix.

**Comment by warmdev** [comment]
This seems to be specific to Docker Toolbox which I assume you are using since you are on OS X. I'll further investigate this while I upgrade the `Dockerfile` to the latest versions of Java and R, and I'll make a note in the `README.md` file.

**Comment by warmdev** [comment]
Added port 7406 to exposed ports list for the event console to work correctly. See 1b8c54f
